#!/usr/bin/env python3
"""
Write cloud-init first-boot configuration onto a mounted Raspberry Pi OS boot
partition.

Raspberry Pi OS Trixie (2026-06 and later) removed the Bookworm-era
`custom.toml` mechanism entirely - the image contains no reference to it, and
the `raspberrypi-sys-mods/firstboot` hook is gone. Headless provisioning is now
done with cloud-init's NoCloud datasource, which reads `user-data`,
`meta-data` and `network-config` from the boot partition.

Settings are taken from the environment so that secrets never appear in argv
(which is world-readable via `ps`):

    PI_HOSTNAME          hostname (default: airprint)
    PI_USER              login account to create (default: pi)
    PI_PASSWORD_HASH     SHA-512 crypt hash, e.g. from `openssl passwd -6`
    PI_TIMEZONE          e.g. America/Los_Angeles
    WIFI_SSID            omit for Ethernet-only
    WIFI_PASSWORD        WPA2 passphrase
    WIFI_COUNTRY         regulatory domain (default: US)

Usage:
    python3 write-cloud-init.py /Volumes/bootfs
    python3 write-cloud-init.py /Volumes/bootfs --from-toml   # reuse custom.toml
"""

import argparse
import json
import os
import re
import sys
import uuid


def read_custom_toml(path):
    """Salvage settings from a Bookworm-era custom.toml so a card that was
    flashed with the old mechanism can be converted without re-entering
    passwords."""
    text = open(path, encoding="utf-8").read()

    def grab(section, key):
        sec = re.search(r"\[" + section + r"\](.*?)(?=\n\[|\Z)", text, re.S)
        if not sec:
            return None
        hit = re.search(r'^' + key + r'\s*=\s*"(.*)"\s*$', sec.group(1), re.M)
        return hit.group(1) if hit else None

    return {
        "PI_HOSTNAME": grab("system", "hostname"),
        "PI_USER": grab("user", "name"),
        "PI_PASSWORD_HASH": grab("user", "password"),
        "PI_TIMEZONE": grab("locale", "timezone"),
        "WIFI_SSID": grab("wlan", "ssid"),
        "WIFI_PASSWORD": grab("wlan", "password"),
        "WIFI_COUNTRY": grab("wlan", "country"),
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("boot", help="Mounted boot partition, e.g. /Volumes/bootfs")
    ap.add_argument("--from-toml", action="store_true",
                    help="Take settings from an existing custom.toml on the card")
    ap.add_argument("--keep-toml", action="store_true",
                    help="Do not delete custom.toml after converting")
    args = ap.parse_args()

    boot = args.boot
    if not os.path.isdir(boot):
        sys.exit(f"Not a directory: {boot}")
    if not os.path.exists(os.path.join(boot, "cmdline.txt")):
        sys.exit(f"{boot} does not look like a Raspberry Pi boot partition.")

    cfg = dict(os.environ)
    toml_path = os.path.join(boot, "custom.toml")
    if args.from_toml:
        if not os.path.exists(toml_path):
            sys.exit(f"No custom.toml found at {toml_path}")
        for k, v in read_custom_toml(toml_path).items():
            if v:
                cfg.setdefault(k, v)

    host = cfg.get("PI_HOSTNAME") or "airprint"
    user = cfg.get("PI_USER") or "pi"
    pw_hash = cfg.get("PI_PASSWORD_HASH") or ""
    tz = cfg.get("PI_TIMEZONE") or "America/Los_Angeles"
    ssid = cfg.get("WIFI_SSID") or ""
    wifi_pw = cfg.get("WIFI_PASSWORD") or ""
    country = cfg.get("WIFI_COUNTRY") or "US"

    if not pw_hash.startswith("$6$"):
        sys.exit("PI_PASSWORD_HASH must be a SHA-512 crypt hash starting with '$6$'.")
    if ssid and not wifi_pw:
        sys.exit("WIFI_SSID given without WIFI_PASSWORD.")

    # JSON strings are valid YAML double-quoted scalars, so this quotes safely.
    q = json.dumps

    groups = ("adm, dialout, cdrom, audio, users, sudo, video, games, "
              "plugdev, input, gpio, spi, i2c, netdev, render, lpadmin")

    user_data = f"""#cloud-config
# Generated by write-cloud-init.py

hostname: {q(host)}
manage_etc_hosts: true
timezone: {q(tz)}

ssh_pwauth: true

users:
  - name: {q(user)}
    gecos: "Raspberry Pi OS"
    shell: /bin/bash
    lock_passwd: false
    passwd: {q(pw_hash)}
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    groups: [{groups}]

chpasswd:
  expire: false
  users:
    - name: {q(user)}
      password: {q(pw_hash)}
      type: hash
"""

    wifi_block = ""
    if ssid:
        wifi_block = f"""
  wifis:
    wlan0:
      dhcp4: true
      optional: true
      regulatory-domain: {q(country)}
      access-points:
        {q(ssid)}:
          password: {q(wifi_pw)}
"""

    network_config = f"""# Generated by write-cloud-init.py
network:
  version: 2

  ethernets:
    eth0:
      dhcp4: true
      optional: true
{wifi_block}"""

    # A new instance_id makes cloud-init treat this as a fresh instance and
    # re-run first-boot config even if the card has already been booted.
    meta_data = f"""# Generated by write-cloud-init.py
dsmode: local
instance_id: {uuid.uuid4()}
"""

    for name, content in (("user-data", user_data),
                          ("network-config", network_config),
                          ("meta-data", meta_data)):
        with open(os.path.join(boot, name), "w", encoding="utf-8", newline="\n") as f:
            f.write(content)
        print(f"  wrote {name} ({len(content)} bytes)")

    open(os.path.join(boot, "ssh"), "w").close()
    print("  created ssh marker")

    if os.path.exists(toml_path) and not args.keep_toml:
        os.remove(toml_path)
        print("  removed custom.toml (ignored by Trixie; held a plaintext Wi-Fi password)")

    net = f'Wi-Fi "{ssid}" ({country}) + Ethernet' if ssid else "Ethernet only"
    print(f"\n  hostname : {host}.local\n  user     : {user}\n  network  : {net}\n  timezone : {tz}")


if __name__ == "__main__":
    main()
